version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 6000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: >
      sh -c "alembic upgrade head &&
            uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
#     #env_file:
#     #  - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=chancho1986
      - DATABASE_NAME=fastapi_test
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=4b98c8d0d8bc9ef73f9588342bed806d96f8233ff0313e5ee27b8139bc32d5a5
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=chancho1986
      - POSTGRES_DB=fastapi_test
    volumes: #store data even after container is down
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: