"""add missin columns to posts table

Revision ID: 1e555e78d663
Revises: 2f8936c293d9
Create Date: 2024-04-17 13:13:45.809573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e555e78d663'
down_revision: Union[str, None] = '2f8936c293d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('edited', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('posts', sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('posts', 'edited_at')
    op.drop_column('posts', 'edited')
    # ### end Alembic commands ###
