name: Build and Deploy code

on: [push, pull_request]
  # push:
    # branches: ['main', 'anotherbranch', ...]
  # pull_request:
    # branches:
      # - 'main'
      # - 'anotherbranch'
      # - 'test_branch'


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: install python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installing all dependencies
        run: pip install -r requirements.txt