name: Build and Deploy code

on: [push, pull_request]
  # push:
    # branches: ['main', 'anotherbranch', ...]
  # pull_request:
    # branches:
      # - 'main'
      # - 'anotherbranch'
      # - 'test_branch'


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: say hi to gian
        run: echo 'hello Gian'